Dev raghu
psd9988/Dashboard_Stocks_App pull request #6
Opened 2022-11-20 17:02 UTC by rjraghutech

2022-11-21 07:17 UTC, Souvikdeb2612 requested changes

2022-11-21 07:17 UTC, Souvikdeb2612 commented on src/Components/Header/Header.js
> +import "../Header/header.css";
format imports

2022-11-21 07:17 UTC, Souvikdeb2612 commented on src/Components/Header/Login.js
> +            <button onClick={() => setUser(true)} className="createBtn">Don't have account..? Sign In</button>
create a separate function for this

2022-11-21 07:17 UTC, Souvikdeb2612 commented on src/Components/Header/Login.js
> +            <button onClick={() => setUser(false)} className="createBtn">Already have account Login...</button>
same as above

2022-11-21 13:26 UTC, rjraghutech commented on src/Components/Header/Login.js
> +            <button onClick={() => setUser(false)} className="createBtn">Already have account Login...</button>
I have updated the requested changes.

2022-11-21 13:27 UTC, rjraghutech commented on src/Components/Header/Header.js
> +import "../Header/header.css";
I have updated the things sir.

2022-11-21 13:27 UTC, rjraghutech commented on src/Components/Header/Login.js
> +            <button onClick={() => setUser(true)} className="createBtn">Don't have account..? Sign In</button>
I have updated the changes sir.

2022-11-22 09:35 UTC, Souvikdeb2612 requested changes

2022-11-22 09:35 UTC, Souvikdeb2612 commented on src/Components/Header/Login.js
>      <button onClick={() => setUser(true)} className="createBtn">Don't have account..? Sign In</button>
create separate function

2022-11-22 09:35 UTC, Souvikdeb2612 commented on src/Components/SideBar/SideBar.js
> +          <button type="button" className="btnside sidebtn">
These are navlinks not buttons

2022-11-22 11:12 UTC, Souvikdeb2612 approved these changes

2022-11-22 11:12 UTC, merged